#pragma once
#ifndef MASTER_LOAD_EVENT_BASE 
#define MASTER_LOAD_EVENT_BASE L"MASTER_LOAD_EVENT."
#endif
#ifndef HOOK_DLL_NT_MASTER_LOAD_EVENT 
#define HOOK_DLL_NT_MASTER_LOAD_EVENT L"\\BaseNamedObjects\\" MASTER_LOAD_EVENT_BASE
#endif


#ifndef USER_MODE_MASTER_LOAD_EVENT 
#define USER_MODE_MASTER_LOAD_EVENT L"Global\\" MASTER_LOAD_EVENT_BASE
#endif

#ifndef INJECTION_SIGNAL_EVENT_BASE
#define INJECTION_SIGNAL_EVENT_BASE L"INJECTION_SIGNAL."
#endif

#ifndef HOOK_DLL_NT_INJECTION_SIGNAL_EVENT
#define HOOK_DLL_NT_INJECTION_SIGNAL_EVENT L"\\BaseNamedObjects\\" INJECTION_SIGNAL_EVENT_BASE
#endif


#ifndef USER_MODE_INJECTION_SIGNAL_EVENT
#define USER_MODE_INJECTION_SIGNAL_EVENT L"Global\\" INJECTION_SIGNAL_EVENT_BASE
#endif