#pragma once
#ifndef MASTER_LOAD_EVENT_BASE 
#define MASTER_LOAD_EVENT_BASE L"MASTER_LOAD_EVENT."
#endif
#ifndef HOOK_DLL_NT_MASTER_LOAD_EVENT 
#define HOOK_DLL_NT_MASTER_LOAD_EVENT L"\\BaseNamedObjects\\" MASTER_LOAD_EVENT_BASE
#endif


#ifndef USER_MODE_MASTER_LOAD_EVENT 
#define USER_MODE_MASTER_LOAD_EVENT L"Global\\" MASTER_LOAD_EVENT_BASE
#endif

#ifndef INJECTION_SIGNAL_EVENT_BASE
#define INJECTION_SIGNAL_EVENT_BASE L"INJECTION_SIGNAL."
#endif

#ifndef HOOK_DLL_NT_INJECTION_SIGNAL_EVENT
#define HOOK_DLL_NT_INJECTION_SIGNAL_EVENT L"\\BaseNamedObjects\\" INJECTION_SIGNAL_EVENT_BASE
#endif

#ifndef HOOK_DLL_LOAD_MUTANT_FMT
#define HOOK_DLL_LOAD_MUTANT_FMT L"\\BaseNamedObjects\\UMHH_DLL_MUTANT.%d"
#endif

#define MASTER_LOADED_SIGNAL_BACK_EVENT_BASE L"MASTER_LOADLED_SIGNAL_BACK."
#ifndef HOOK_DLL_NT_MASTER_LOADED_SIGNAL_BACK_EVENT
#define HOOK_DLL_NT_MASTER_LOADED_SIGNAL_BACK_EVENT L"\\BaseNamedObjects\\" MASTER_LOADED_SIGNAL_BACK_EVENT_BASE
#endif

#ifndef HOOK_DLL_UM_MASTER_LOADED_SIGNAL_BACK_EVENT
#define HOOK_DLL_UM_MASTER_LOADED_SIGNAL_BACK_EVENT L"Global\\" MASTER_LOADED_SIGNAL_BACK_EVENT_BASE
#endif

#ifndef USER_MODE_INJECTION_SIGNAL_EVENT
#define USER_MODE_INJECTION_SIGNAL_EVENT L"Global\\" INJECTION_SIGNAL_EVENT_BASE
#endif


#define UM_STOP_SIGNAL_FILE_PATH L"C:\\Users\\Public\\stop_umhh_boot_start"
#define DRIVER_STOP_SIGNAL_FILE_PATH L"\\??\\" UM_STOP_SIGNAL_FILE_PATH

#define LOCATOR_SIGNAL_EVENT L"Global\\LOCATOR_SIGNAL_EVENT"
#define LOCATOR_IPC_FILE_PATH L"C:\\Users\\Public\\locator.bin"

#define HOOK_CODE_EXPORT_X86 "HookCodeWin32"
#define HOOK_CODE_EXPORT_X64 "HookCodeX64"

#define HOOK_CODE_TEMP_DIR_NAME L"hookcode_dll_temp"

#define KERNEL_32_X86 "\\Windows\\SysWOW64\\kernel32.dll"
#define KERNEL_32_X64 "\\Windows\\System32\\kernel32.dll"

#define WIDEN2(x) L##x
#define WIDEN(x) WIDEN2(x)



// Simple module list node returned by PhBuildModuleListWow64
typedef struct _PH_MODULE_LIST_NODE {
	struct _PH_MODULE_LIST_NODE* Next;
	void* Base;
	unsigned long Size; // SizeOfImage if known; 0 if unknown
	wchar_t* Path;      // Full NT path of module
} PH_MODULE_LIST_NODE, *PPH_MODULE_LIST_NODE;

#ifndef UMHH_OB_CALLBACK_DEVICE
#define UMHH_OB_CALLBACK_DEVICE L"\\\\.\\UMHHObCallbackCtl"
#endif