#pragma once
#ifndef MASTER_LOAD_EVENT_BASE 
#define MASTER_LOAD_EVENT_BASE L"MASTER_LOAD_EVENT."
#endif
#ifndef HOOK_DLL_NT_MASTER_LOAD_EVENT 
#define HOOK_DLL_NT_MASTER_LOAD_EVENT L"\\BaseNamedObjects\\" MASTER_LOAD_EVENT_BASE
#endif
#ifndef USER_MODE_MASTER_LOAD_EVENT 
#define USER_MODE_MASTER_LOAD_EVENT L"Global\\" MASTER_LOAD_EVENT_BASE
#endif